name: .NET Core (branch)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  net-framework:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build .NET Framework sample
      run: dotnet build test_integration\Websocket.Client.Sample.NetFramework\Websocket.Client.Sample.NetFramework.csproj --configuration Release --framework net472
    - name: Build .NET Framework benchmarks
      run: dotnet build benchmarks\Websocket.Client.Benchmarks\Websocket.Client.Benchmarks.csproj --configuration Release --framework net472
